#!/bin/bash

FLAV=${1:-Clyde}
TREE=tepcs

stash_stats() {
	lun=$1
	node=$2
	froot=$3
	./splitu32 $froot.stats 8

	
	(cd LOG; ln -sf $FLAV.$lun.stats.0 $FLAV.$lun.stats.DI32)
	(cd LOG; ln -sf $FLAV.$lun.stats.1 $FLAV.$lun.stats.TL)
	(cd LOG; ln -sf $FLAV.$lun.stats.3 $FLAV.$lun.stats.GTS0)
	(cd LOG; ln -sf $FLAV.$lun.stats.4 $FLAV.$lun.stats.GTS1)
	(cd LOG; ln -sf $FLAV.$lun.stats.5 $FLAV.$lun.stats.PC)

	./mdsput $TREE $node.DI32 LOG/$FLAV.$lun.stats.DI32
	./mdsput $TREE $node.STATS.TL   LOG/$FLAV.$lun.stats.TL
	./mdsput $TREE $node.STATS.GTS0 LOG/$FLAV.$lun.stats.GTS0
	./mdsput $TREE $node.STATS.GTS1 LOG/$FLAV.$lun.stats.PC
}

stash_AO() {
	lun=$1
	node=$2
	froot=$3
	
#	for ch_file in $froot.AO.???; do
	for ch_file in `ls $froot.AO.???`; do
		ch=${ch_file##*.}
		echo ./mdsput $TREE $node.AO.CH$ch $ch_file s16
		./mdsput $TREE $node.AO.CH$ch $ch_file s16 #--format short
	done
}

stash_DO() {
	lun=$1
	node=$2
	froot=$3
	if [ -e $froot.DO ]; then
		echo ./mdsput $TREE $node.DO32 $froot.DO
		./mdsput $TREE $node.DO32 $froot.DO # --format unsigned
	fi
}

stash_all() {
    case $1 in
	0) node=acq2106_032;;
	1) node=acq2106_033;;
	*) echo BAD UUT; exit;;
    esac
    froot=LOG/$FLAV.$1	
    
    stash_stats $1 $node $froot
    if [ $node == "acq2106_033" ]; then stash_AO $1 $node $froot; fi
    stash_DO $1 $node $froot
}

stash_all 0
stash_all 1

