#!/bin/bash

export LLC_TRG=ext LLC_CLK=ext
export UUTS="acq2106_032 acq2106_033"

gofer() {
	for uut in $UUTS
	do
		./scripts/tepcs-shot-control-script $uut $1
	done
}

gofer init_2106
gofer start_stream

echo "HIT T to initiate trigger from acq2106_032"
read trg
[ "x$trg" = "xT" ] && ./scripts/toggle-hdmi-trigger acq2106_032
echo run-both hit CR to end
read enough

gofer cleanup


