#!/usr/bin/bash
[ -d scripts ] && cd scripts

# MUST set remote ip-address
REMIP=${1:-acq2106_032}


source afhba-common

SC=0

remote_cmd $SC SIG:SYNC_BUS_OUT:TRG=1
remote_cmd $SC SIG:SYNC_BUS_OUT:TRG=0

